#!/bin/bash

altStore="/var/containers/Bundle/Application/*/AltStore.app/Info.plist"
unc0verPath="$(dirname $(find /var/containers/Bundle/Application/ -mindepth 3 -maxdepth 3 -iname unc0ver) 2>/dev/null)/Info.plist"
deltaFullPath="$(dirname $(find /var/containers/Bundle/Application/ -mindepth 3 -maxdepth 3 -iname DSDeltaCore.bundle) 2>/dev/null)/Info.plist"
deltaLitePath="$(dirname $(dirname $(find /var/containers/Bundle/Application/ -mindepth 4 -maxdepth 4 -iname DeltaCore.framework) 2>/dev/null) 2>/dev/null)/Info.plist"

if test -f $altStore; then
    altInfo=$(defaults read $altStore CFBundleIdentifier)
    echo "Renaming AltStore Icon..."
	mv -f "/Library/Themes/YourTheme.theme/IconBundles/toBeRenamed.com.rileytestut.AltStore-large.png" "/Library/Themes/YourTheme.theme/IconBundles/$altInfo-large.png"
    echo $altInfo > "/Library/Themes/YourTheme.theme/Saved Locations/AltStore.txt"
fi

if test -f $unc0verPath; then
    unc0verInfo=$(defaults read $unc0verPath CFBundleIdentifier)
    echo "Renaming Unc0ver Icon..."
    mv -f "/Library/Themes/YourTheme.theme/IconBundles/toBeRenamed.science.xnu.undecimus-large.png" "/Library/Themes/YourTheme.theme/IconBundles/$unc0verInfo-large.png"
    echo $unc0verInfo > "/Library/Themes/YourTheme.theme/Saved Locations/Unc0ver.txt"
fi

if test -f $deltaFullPath; then
    deltaFullInfo=$(defaults read $deltaFullPath CFBundleIdentifier)
    echo "Renaming Delta Icon..."
	mv -f "/Library/Themes/YourTheme.theme/IconBundles/toBeRenamed.com.rileytestut.Delta-large.png" "/Library/Themes/YourTheme.theme/IconBundles/$deltaFullInfo-large.png"
    echo $deltaFullInfo > "/Library/Themes/YourTheme.theme/Saved Locations/Delta.txt"
fi

if test -f $deltaLitePath; then
    deltaLiteInfo=$(defaults read $deltaLitePath CFBundleIdentifier)
    echo "Renaming Delta Lite Icon..."
    mv -f "/Library/Themes/YourTheme.theme/IconBundles/toBeRenamed.com.rileytestut.Delta.Lite-large.png" "/Library/Themes/YourTheme.theme/IconBundles/$deltaLiteInfo-large.png"
    echo $deltaLiteInfo > "/Library/Themes/YourTheme.theme/Saved Locations/DeltaLite.txt"
fi

echo "All done!"
echo "Thank you for using YourTheme!"
echo "Script made by Dave1482"

        declare -a cydia
        cydia=($CYDIA)

        if [[ ${CYDIA+@} ]]; then
            eval "echo 'finish:restart' >&${cydia[0]}"
        fi

exit 0
