#!/bin/bash

# Replace YourTheme with the theme folder name without the .theme extension (do not use the full path)
themeName="YourTheme"

echo "Cleaning Up..."

altStoreSave="/Library/Themes/$themeName.theme/Saved Locations/AltStore.txt"
unc0verSave="/Library/Themes/$themeName.theme/Saved Locations/Unc0ver.txt"
deltaFullSave="/Library/Themes/$themeName.theme/Saved Locations/Delta.txt"
deltaLiteSave="/Library/Themes/$themeName.theme/Saved Locations/DeltaLite.txt"

# Move files back to original names so the package manager removes the package correctly
if test -f "$altStoreSave"; then
    altInfo=$(cat "$altStoreSave")
	mv -f "/Library/Themes/$themeName.theme/IconBundles/$altInfo-large.png" "/Library/Themes/$themeName.theme/IconBundles/toBeRenamed.com.rileytestut.AltStore-large.png"
	rm -f "$altStoreSave"
fi
if test -f "$unc0verSave"; then
    unc0verInfo=$(cat "$unc0verSave")
	mv -f "/Library/Themes/$themeName.theme/IconBundles/$unc0verInfo-large.png" "/Library/Themes/$themeName.theme/IconBundles/toBeRenamed.science.xnu.undecimus-large.png"
	rm -f "$unc0verSave"
fi
if test -f "$deltaFullSave"; then
    deltaFullInfo=$(cat "$deltaFullSave")
	mv -f "/Library/Themes/$themeName.theme/IconBundles/$deltaFullInfo-large.png" "/Library/Themes/$themeName.theme/IconBundles/toBeRenamed.com.rileytestut.Delta-large.png"
	rm -f "$deltaFullSave"
fi
if test -f "$unc0verSave"; then
    deltaLiteInfo=$(cat "$deltaLiteSave")
	mv -f "/Library/Themes/$themeName.theme/IconBundles/$deltaLiteInfo-large.png" "/Library/Themes/$themeName.theme/IconBundles/toBeRenamed.com.rileytestut.Delta.Lite-large.png"
	rm -f "$deltaLiteSave"
fi

# Remove folder created by script
if [[ -d "/Library/Themes/$themeName.theme/Saved Locations/" ]]; then
    rm -rf "/Library/Themes/$themeName.theme/Saved Locations/" 2>/dev/null
fi
echo "All done!"
echo "Cleanup Script by Dave1482"
exit 0

